// Auto-generated by scripts/css-to-ts.mjs. Do not edit directly.
const cssText = "\n.shadow-preset-select-control {\n    min-width: 130px;\n}\n.shadow-preset-select-control .shadow-preset-trigger {\n    justify-content: space-between;\n    white-space: nowrap;\n}\n.shadow-preset-select-control .shadow-preset-menu {\n    max-height: 260px;\n}\n\n";

export default cssText;
