import type { DiagramHintPoolItem } from "./hint.types";

/**
 * Discoverability hints sourced from currently implemented editor tools,
 * interaction gestures, and keyboard shortcuts.
 */
export const DIAGRAM_HINT_POOL: readonly DiagramHintPoolItem[] = [
    {
        id: 'interaction-select-rect',
        fallbackMessage: 'Drag on empty canvas to create a selection rectangle, or hold R while dragging to force marquee over shapes.',
        category: 'interaction',
        access: ['canvas'],
    },
    {
        id: 'interaction-toggle-select',
        fallbackMessage: 'Use Cmd/Ctrl+click to toggle nodes in the current selection.',
        category: 'interaction',
        access: ['canvas', 'shortcut'],
    },
    {
        id: 'interaction-pan-space',
        fallbackMessage: 'Hold Space and drag to pan the canvas.',
        category: 'interaction',
        access: ['canvas'],
    },
    {
        id: 'interaction-resize-aspect',
        fallbackMessage: 'Hold Shift while resizing to preserve aspect ratio.',
        category: 'interaction',
        access: ['canvas', 'shortcut'],
        minSelectionCount: 1,
    },
    {
        id: 'interaction-rotate-snap',
        fallbackMessage: 'Hold Shift while rotating to snap angle in 15-degree increments.',
        category: 'interaction',
        access: ['canvas', 'shortcut'],
        minSelectionCount: 1,
    },
    {
        id: 'interaction-connection-add-point',
        fallbackMessage: 'Alt+drag a connection segment to insert a new point.',
        category: 'interaction',
        access: ['canvas', 'shortcut'],
        requiresConnectionSelection: true,
    },
    {
        id: 'interaction-connection-remove-point',
        fallbackMessage: 'Alt+click and drag over a connection point to remove that point.',
        category: 'interaction',
        access: ['canvas', 'shortcut'],
        requiresConnectionSelection: true,
    },

    {
        id: 'shortcut-undo',
        fallbackMessage: 'Undo with Cmd/Ctrl+Z.',
        category: 'shortcut',
        actionId: 'undo',
        shortcut: ['Cmd+Z', 'Ctrl+Z'],
        access: ['shortcut', 'toolbar'],
    },
    {
        id: 'shortcut-redo',
        fallbackMessage: 'Redo with Cmd/Ctrl+Shift+Z or Cmd/Ctrl+Y.',
        category: 'shortcut',
        actionId: 'redo',
        shortcut: ['Cmd+Shift+Z', 'Ctrl+Shift+Z', 'Cmd+Y', 'Ctrl+Y'],
        access: ['shortcut', 'toolbar'],
    },
    {
        id: 'shortcut-copy',
        fallbackMessage: 'Copy selected nodes.',
        category: 'clipboard',
        actionId: 'copy',
        shortcut: ['Cmd+C', 'Ctrl+C'],
        access: ['shortcut', 'toolbar'],
        minSelectionCount: 1,
    },
    {
        id: 'shortcut-paste',
        fallbackMessage: 'Paste nodes from clipboard.',
        category: 'clipboard',
        actionId: 'paste',
        shortcut: ['Cmd+V', 'Ctrl+V'],
        access: ['shortcut', 'toolbar'],
    },
    {
        id: 'shortcut-cut',
        fallbackMessage: 'Cut selected nodes.',
        category: 'clipboard',
        actionId: 'cut',
        shortcut: ['Cmd+X', 'Ctrl+X'],
        access: ['shortcut', 'toolbar'],
        minSelectionCount: 1,
    },
    {
        id: 'shortcut-delete',
        fallbackMessage: 'Delete selected nodes.',
        category: 'clipboard',
        actionId: 'delete',
        shortcut: ['Delete', 'Backspace'],
        access: ['shortcut', 'toolbar'],
        minSelectionCount: 1,
    },
    {
        id: 'shortcut-duplicate',
        fallbackMessage: 'Duplicate selection with Cmd/Ctrl+D.',
        category: 'clipboard',
        actionId: 'duplicate',
        shortcut: ['Cmd+D', 'Ctrl+D'],
        access: ['shortcut', 'toolbar'],
        minSelectionCount: 1,
    },
    {
        id: 'shortcut-copy-style',
        fallbackMessage: 'Copy styles from the selected node.',
        category: 'clipboard',
        actionId: 'copy-styles',
        shortcut: ['Cmd+Shift+C', 'Ctrl+Shift+C'],
        access: ['shortcut', 'toolbar'],
        minSelectionCount: 1,
    },
    {
        id: 'shortcut-paste-style',
        fallbackMessage: 'Paste styles to selected nodes.',
        category: 'clipboard',
        actionId: 'paste-styles',
        shortcut: ['Cmd+Shift+V', 'Ctrl+Shift+V'],
        access: ['shortcut', 'toolbar'],
        minSelectionCount: 1,
    },
    {
        id: 'shortcut-select-all',
        fallbackMessage: 'Select all nodes with Cmd/Ctrl+A.',
        category: 'shortcut',
        shortcut: ['Cmd+A', 'Ctrl+A'],
        access: ['shortcut'],
    },
    {
        id: 'shortcut-toggle-guides',
        fallbackMessage: 'Toggle guides (visibility and snapping).',
        category: 'view',
        actionId: 'toggle-guides',
        shortcut: ['Cmd+Alt+L', 'Ctrl+Alt+L'],
        access: ['shortcut', 'toolbar'],
    },
    {
        id: 'shortcut-toggle-grid',
        fallbackMessage: 'Toggle snapping grid (shows grid and enables forced snapping).',
        category: 'view',
        actionId: 'toggle-grid',
        shortcut: ['Cmd+Alt+G', 'Ctrl+Alt+G'],
        access: ['shortcut', 'toolbar'],
    },
    {
        id: 'shortcut-toggle-visual-grid',
        fallbackMessage: 'Toggle visual-only grid (grid visibility without forced snapping).',
        category: 'view',
        actionId: 'toggle-visual-grid',
        shortcut: ['Cmd+Alt+Shift+G', 'Ctrl+Alt+Shift+G'],
        access: ['shortcut', 'toolbar'],
    },
    // {
    //     id: 'shortcut-toggle-guides-visibility',
    //     fallbackMessage: 'Toggle guides (visibility and snapping).',
    //     category: 'view',
    //     actionId: 'show-guides',
    //     shortcut: ['Cmd+Alt+L', 'Ctrl+Alt+L'],
    //     access: ['shortcut', 'toolbar'],
    // },
    // {
    //     id: 'shortcut-toggle-guides-snap',
    //     fallbackMessage: 'Guide snapping follows the guides toggle shortcut.',
    //     category: 'view',
    //     actionId: 'snap-guides',
    //     access: ['toolbar'],
    // },
    // {
    //     id: 'shortcut-toggle-grid-visibility',
    //     fallbackMessage: 'Toggle snapping grid (shows grid and enables forced snapping).',
    //     category: 'view',
    //     actionId: 'show-grid',
    //     shortcut: ['Cmd+Alt+G', 'Ctrl+Alt+G'],
    //     access: ['shortcut', 'toolbar'],
    // },
    // {
    //     id: 'shortcut-toggle-grid-snap',
    //     fallbackMessage: 'Toggle visual-only grid (grid visibility without forced snapping).',
    //     category: 'view',
    //     actionId: 'snap-grid',
    //     shortcut: ['Cmd+Alt+Shift+G', 'Ctrl+Alt+Shift+G'],
    //     access: ['shortcut', 'toolbar'],
    // },
    {
        id: 'shortcut-nudge-large',
        fallbackMessage: 'Use Shift+Arrow keys to move selection (or pan when nothing is selected).',
        category: 'layout',
        shortcut: 'Shift+Arrow',
        access: ['shortcut', 'canvas'],
    },
    {
        id: 'shortcut-nudge-small',
        fallbackMessage: 'Use Cmd/Ctrl+Alt+Arrow keys for fine 0.5px nudging.',
        category: 'layout',
        shortcut: ['Cmd+Alt+Arrow', 'Ctrl+Alt+Arrow'],
        access: ['shortcut', 'canvas'],
        minSelectionCount: 1,
    },
    {
        id: 'shortcut-text-bold',
        fallbackMessage: 'Toggle bold text with Cmd/Ctrl+B.',
        category: 'text',
        actionId: 'text-bold',
        shortcut: ['Cmd+B', 'Ctrl+B'],
        access: ['shortcut', 'toolbar', 'inspector'],
        requiresTextCapableSelection: true,
    },
    {
        id: 'shortcut-text-italic',
        fallbackMessage: 'Toggle italic text with Cmd/Ctrl+I.',
        category: 'text',
        actionId: 'text-italic',
        shortcut: ['Cmd+I', 'Ctrl+I'],
        access: ['shortcut', 'toolbar', 'inspector'],
        requiresTextCapableSelection: true,
    },

    {
        id: 'action-fit-all',
        fallbackMessage: 'Use the toolbar [Fit All] action to frame all nodes quickly.',
        category: 'view',
        actionId: 'fit-all',
        shortcut: ['Cmd+Alt+F', 'Ctrl+Alt+F'],
        access: ['shortcut', 'toolbar'],
    },
    {
        id: 'action-fit-horizontally',
        fallbackMessage: 'Use the toolbar [Fit to Horizontal Size] action to focus the canvas on horizontal workspace.',
        category: 'view',
        actionId: 'fit-horizontally',
        shortcut: ['Cmd+Alt+H', 'Ctrl+Alt+H'],
        access: ['shortcut', 'toolbar'],
    },
    {
        id: 'action-align',
        fallbackMessage: 'Select multiple nodes, then use toolbar align/distribute actions.',
        category: 'layout',
        access: ['toolbar'],
        minSelectionCount: 2,
    },
    {
        id: 'action-tool-palette-drag',
        fallbackMessage: 'For supported tools, drag from the tool palette to draw directly on canvas.',
        category: 'tool',
        access: ['palette', 'canvas'],
    },
    {
        id: 'action-tool-palette-click',
        fallbackMessage: 'Click a tool in the palette to make it active for the next creation.',
        category: 'tool',
        access: ['palette'],
    },
] as const;
