// Auto-generated by scripts/css-to-ts.mjs. Do not edit directly.
const cssText = ".diagram-editor {\n    --diagram-ui-surface: rgb(36, 36, 36);\n    --diagram-ui-surface-elevated: rgb(48, 48, 48);\n    --diagram-ui-text: white;\n    --diagram-ui-text-muted: darkgray;\n    --diagram-ui-accent: darkgreen;\n    --diagram-ui-accent-contrast: lime;\n    --diagram-ui-border: rgb(80, 80, 80);\n    --diagram-ui-control-radius: 4px;\n\n    --diagram-inspector-base: 128, 168, 128;\n    --diagram-foreground-mixer: white;\n    --diagram-background-mixer: #0f172a;\n}";

export default cssText;
