// Auto-generated by scripts/css-to-ts.mjs. Do not edit directly.
const cssText = ".gp-trigger {\n    display: block;\n    width: 100%;\n    padding: 6px 8px;\n    cursor: pointer;\n    appearance: none;\n    border: var(--diagram-ui-border-width, 1px) solid var(--diagram-ui-border, rgba(15, 23, 42, 0.15));\n    border-radius: var(--diagram-ui-control-radius, 10px);\n    background: var(--diagram-ui-surface, rgba(255, 255, 255, 0.88));\n    position: relative;\n    box-sizing: border-box;\n}\n\n.gp-trigger .gp-swatch {\n    width: 100%;\n    min-height: 18px;\n    border-radius: 5px;\n    border: var(--diagram-ui-border-width, 1px) solid var(--diagram-ui-border, rgba(15, 23, 42, 0.2));\n}";

export default cssText;
