import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');
const cssSourceRoot = path.join(projectRoot, 'src', 'css');
const cssGeneratedRoot = path.join(projectRoot, 'src', 'css_generated');

async function collectCssFiles(dir) {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    const files = [];

    for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            files.push(...await collectCssFiles(fullPath));
            continue;
        }
        if (entry.isFile() && entry.name.endsWith('.css')) {
            files.push(fullPath);
        }
    }

    return files;
}

function toModuleSource(css) {
    const payload = JSON.stringify(css);
    return [
        '// Auto-generated by scripts/css-to-ts.mjs. Do not edit directly.',
        `const cssText = ${payload};`,
        '',
        'export default cssText;',
        ''
    ].join('\n');
}

async function writeIfChanged(targetPath, content) {
    try {
        const current = await fs.readFile(targetPath, 'utf8');
        if (current === content) {
            return;
        }
    }
    catch {
        // File does not exist; write below.
    }

    await fs.writeFile(targetPath, content, 'utf8');
}

async function run() {
    const cssFiles = await collectCssFiles(cssSourceRoot);

    for (const cssFile of cssFiles) {
        const css = await fs.readFile(cssFile, 'utf8');
        const relativeCssPath = path.relative(cssSourceRoot, cssFile);
        const modulePath = path.join(cssGeneratedRoot, relativeCssPath.replace(/\.css$/, '.css.ts'));
        const moduleSource = toModuleSource(css);

        await fs.mkdir(path.dirname(modulePath), { recursive: true });
        await writeIfChanged(modulePath, moduleSource);
    }

    console.log(`Embedded ${cssFiles.length} CSS file(s) as TypeScript modules.`);
}

run().catch((error) => {
    console.error('[css:embed] Failed to generate CSS modules.');
    console.error(error);
    process.exitCode = 1;
});
